name: shimaa_fitness
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^9.2.4
  injectable: ^2.5.0
  shared_preferences: ^2.5.3
  firebase_database: ^11.3.7
  internet_connection_checker: ^3.0.1
  logger: ^2.5.0
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  easy_localization: ^3.0.7+1
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.0.0

flutter:
  uses-material-design: true
